### ISSUE TITLE
Saving all browser tabs as tab sets

### ISSUE THREAD

**Issue by dustinblake** [richardkall/pinboard-pro-chrome-extension#1]
First, thanks for this great extension! It would be perfect if it was able to perform the "Save tabs set to Pinboard" function... any chance it's on your roadmap?

**Comment by richardkall** [comment]
Thank you, glad you like it! I'm not really sure how to implement this at the moment, but I might look into it in the future. I'll keep this open. Feel free to fork the project and try it out yourself in the meantime.

**Comment by Zegnat** [comment]
@dustinblake are tab sets working for you in any other extension / app? I would love to look into, but am pessimistic about the chances.

Last time I checked, tab sets were broken in the Safari extension. I looked into reverse engineering it but the code seemed to be fine and I even expect something broke on Pinboard’s side. Also sent an email to Maciej about it back in January, but never received a reply.

**Comment by amrkhalifeh** [comment]
You can use this [Chrome extension](https://chrome.google.com/webstore/detail/save-tabs-set-to-pinboard/ehddnmgofimbganchpecibdhmdlaghno).

**Comment by Zegnat** [comment]
@amrkhalifeh before I look into how they implemented it, can you confirm that extension is actually still working?

**Comment by amrkhalifeh** [comment]
Yep, I use it myself in Chrome. I came across your project while looking for an extension that does the same for Safari, which I haven't found, sadly.

**Comment by Zegnat** [comment]
@amrkhalifeh, there is a PR for the save all tabs function now :smile: thanks for the prompt!

I am afraid I haven’t done Safari development [since the 2015 Developer Program change](https://indieweb.org/Safari_Extensions#Controversy) and will not be able to assist on a Safari port.

**Comment by amrkhalifeh** [comment]
Glad I could help! :) Yeah, I know Apple's dev program has made it harder for developers to justify the cost. Not sure Safari on the Mac will ever have more than a handful of extensions. 😞 Thanks anyway, Zegnat.

**Comment by dustinblake** [comment]
Just wanted to share that there's a Safari extension that saves all tabs (it's not directly mentioned on the pinboard resources page for some reason):

https://pinboard.in/resources/safari/save_tabs

**Comment by amrkhalifeh** [comment]
Thanks, @dustinblake! I'd already tried that extension but I didn't work when I tried it. I'd assumed it was no longer maintained. However, I tried it again just before typing this reply and it worked on the latest version of Safari. So thanks for prompting me to try it again! 😊
