### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by Strajk** [richardkall/pinboard-pro-chrome-extension#2]
I would love to use this, but I'm Safari user (for complicated reasons :))

Is someone experienced with extensions able and willing to fork this project to Safari?
If not, I could try it, but I will have to learn how first :)

**Comment by richardkall** [comment]
@Strajk Is this still of interest to you? Or should we close this issue? I'm not a Safari user myself unfortunately.

**Comment by Strajk** [comment]
@richardkall switched to Chrome looong time ago :) anyway, thx for replying
