### ISSUE TITLE
Close the popup after click

### ISSUE THREAD

**Issue by asgerhallas** [richardkall/pinboard-pro-chrome-extension#3]
Thank you for a fine extension! :)

Clicking one of the items in the popup does not close the popup, which I think would be expected? I have to manually set focus somewhere else to close it.

**Comment by richardkall** [comment]
Thank you, glad you like it!

I can't reproduce this issue and it has never happened for me. Do you get any errors in the console? I'm guessing it could be a collision with another extension or something.
